#!/usr/bin/env bb
;; Acceptance entrypoint generator.
;;
;; Reads the APS intermediate representation produced by `gherkin-parser` and
;; emits one XCTest method per scenario example row. Each method hands the
;; runtime the scenario's steps with every `<placeholder>` already replaced by
;; that row's value, so the generated file holds no assertions of its own — the
;; project step handlers own all of those.

(ns generate
  (:require [babashka.fs :as fs]
            [cheshire.core :as json]
            [clojure.string :as str]))

(defn- substitute
  "Replaces every <placeholder> in `text` with its value from `example`."
  [text example]
  (reduce (fn [acc [k v]]
            (str/replace acc (str "<" (name k) ">") (str v)))
          text
          example))

(defn- swift-string [s]
  (str "\"" (-> s (str/replace "\\" "\\\\") (str/replace "\"" "\\\"")) "\""))

(defn- identifier
  "A Swift-safe method-name fragment."
  [s]
  (-> s
      (str/replace #"[^A-Za-z0-9]+" "_")
      (str/replace #"^_+|_+$" "")))

(defn- rows
  "One entry per scenario example row. A scenario with no Examples table still
  runs once, with no substitutions."
  [scenario]
  (let [examples (or (seq (:examples scenario)) [{}])]
    (map-indexed (fn [index example]
                   {:index (inc index)
                    :steps (map #(substitute (:text %) example) (:steps scenario))})
                 examples)))

(defn- method [feature scenario row]
  (let [name (str "test_" (identifier (:name scenario)) "_row" (:index row))
        steps (->> (:steps row) (map swift-string) (str/join ",\n                "))]
    (str "    func " name "() async throws {\n"
         "        try await AcceptanceRuntime.run(\n"
         "            feature: " (swift-string (:name feature)) ",\n"
         "            scenario: " (swift-string (:name scenario)) ",\n"
         "            steps: [\n                " steps "\n            ]\n"
         "        )\n"
         "    }\n")))

(defn- class-source [feature]
  (let [class-name (str (identifier (:name feature)) "AcceptanceTests")]
    (str "@MainActor\n"
         "final class " class-name ": XCTestCase {\n\n"
         (->> (:scenarios feature)
              (mapcat (fn [scenario] (map #(method feature scenario %) (rows scenario))))
              (str/join "\n"))
         "}\n")))

(defn- read-ir [f]
  (let [ir (json/parse-string (slurp f) true)]
    (when-not (and (:name ir) (:scenarios ir))
      (throw (ex-info (str "not an APS feature IR: " f) {:file f})))
    ir))

(defn generate [ir-files]
  (str "// Generated by acceptance/generate.clj from the APS intermediate\n"
       "// representation. Do not edit by hand — rerun bin/acceptance.\n\n"
       "import XCTest\n@testable import Sotto\n\n"
       (->> ir-files
            (map read-ir)
            (map class-source)
            (str/join "\n"))))

(defn -main [& args]
  (let [out (first args)
        ir-files (sort (rest args))]
    (when (or (nil? out) (empty? ir-files))
      (println "usage: generate.clj <out.swift> <ir.json>...")
      (System/exit 2))
    (fs/create-dirs (fs/parent out))
    (spit out (generate ir-files))
    (println "GENERATED" out)))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
