(ns acceptance.generator
  "Turns APS feature IR into the executable XCTest source.

  The generated methods are bound to scenario STRUCTURE, not to example values:
  each one names the scenario and example row it runs, and the runtime reads the
  step text and the row's values out of whatever IR it is given. That is what
  lets acceptance mutation reuse one built test bundle across every mutated IR
  instead of regenerating and rebuilding per mutation.

  Pure: every function here maps data to data, so the generated text is
  characterized by specs without touching the filesystem."
  (:require [clojure.string :as str]))

(defn swift-string [s]
  (str "\"" (-> s (str/replace "\\" "\\\\") (str/replace "\"" "\\\"")) "\""))

(defn identifier
  "A Swift-safe method-name fragment."
  [s]
  (-> s
      (str/replace #"[^A-Za-z0-9]+" "_")
      (str/replace #"^_+|_+$" "")))

(defn rows
  "One entry per scenario example row, carrying the row's position in the IR. A
  scenario with no Examples table still runs once, against an empty row."
  [scenario]
  (let [examples (or (seq (:examples scenario)) [{}])]
    (map-indexed (fn [index _] {:index (inc index) :example-index index}) examples)))

(defn method [feature scenario-index scenario row]
  (str "    func test_" (identifier (:name scenario)) "_row" (:index row) "() throws {\n"
       "        try AcceptanceRuntime.run(\n"
       "            feature: " (swift-string (:name feature)) ",\n"
       "            scenario: " (swift-string (:name scenario)) ",\n"
       "            scenarioIndex: " scenario-index ",\n"
       "            exampleIndex: " (:example-index row) "\n"
       "        )\n"
       "    }\n"))

(defn class-source [feature]
  (str "@MainActor\n"
       "final class " (identifier (:name feature)) "AcceptanceTests: XCTestCase {\n\n"
       (->> (:scenarios feature)
            (map-indexed (fn [scenario-index scenario]
                           (map #(method feature scenario-index scenario %) (rows scenario))))
            (apply concat)
            (str/join "\n"))
       "}\n"))

(defn feature-ir?
  "An APS feature IR names the feature and carries its scenarios."
  [ir]
  (boolean (and (:name ir) (:scenarios ir))))

(defn source
  "The complete generated Swift file for `features`, in the given order."
  [features]
  (str "// Generated by acceptance/generate.clj from the APS intermediate\n"
       "// representation. Do not edit by hand — rerun bin/acceptance.\n"
       "//\n"
       "// Each method names the scenario and example row it runs. The step text\n"
       "// and the row's values come from the IR the runtime is pointed at, so\n"
       "// one build of this file runs any mutated IR.\n\n"
       "import XCTest\n@testable import Sotto\n\n"
       (->> features (map class-source) (str/join "\n"))))

;; clj-mutate-manifest-begin
;; {:version 1, :tested-at "2026-08-26T16:55:36.755484+05:30", :module-hash "307548491", :forms [{:id "form/0/ns", :kind "ns", :line 1, :end-line nil, :hash "981722329"} {:id "defn/swift-string", :kind "defn", :line 14, :end-line nil, :hash "-351955768"} {:id "defn/identifier", :kind "defn", :line 17, :end-line nil, :hash "1345382047"} {:id "defn/rows", :kind "defn", :line 24, :end-line nil, :hash "258165909"} {:id "defn/method", :kind "defn", :line 31, :end-line nil, :hash "-1494359534"} {:id "defn/class-source", :kind "defn", :line 41, :end-line nil, :hash "1184949067"} {:id "defn/feature-ir?", :kind "defn", :line 51, :end-line nil, :hash "-1682509703"} {:id "defn/source", :kind "defn", :line 56, :end-line nil, :hash "-759417809"}]}
;; clj-mutate-manifest-end
