(ns acceptance.generator
  "Turns APS feature IR into the executable XCTest source.

  Pure: every function here maps data to data, so the generated text is
  characterized by specs without touching the filesystem."
  (:require [clojure.string :as str]))

(defn substitute
  "Replaces every <placeholder> in `text` with its value from `example`."
  [text example]
  (reduce (fn [acc [k v]]
            (str/replace acc (str "<" (name k) ">") (str v)))
          text
          example))

(defn swift-string [s]
  (str "\"" (-> s (str/replace "\\" "\\\\") (str/replace "\"" "\\\"")) "\""))

(defn identifier
  "A Swift-safe method-name fragment."
  [s]
  (-> s
      (str/replace #"[^A-Za-z0-9]+" "_")
      (str/replace #"^_+|_+$" "")))

(defn rows
  "One entry per scenario example row. A scenario with no Examples table still
  runs once, with no substitutions."
  [scenario]
  (let [examples (or (seq (:examples scenario)) [{}])]
    (map-indexed (fn [index example]
                   {:index (inc index)
                    :steps (map #(substitute (:text %) example) (:steps scenario))})
                 examples)))

(defn method [feature scenario row]
  (let [name (str "test_" (identifier (:name scenario)) "_row" (:index row))
        steps (->> (:steps row) (map swift-string) (str/join ",\n                "))]
    (str "    func " name "() async throws {\n"
         "        try await AcceptanceRuntime.run(\n"
         "            feature: " (swift-string (:name feature)) ",\n"
         "            scenario: " (swift-string (:name scenario)) ",\n"
         "            steps: [\n                " steps "\n            ]\n"
         "        )\n"
         "    }\n")))

(defn class-source [feature]
  (let [class-name (str (identifier (:name feature)) "AcceptanceTests")]
    (str "@MainActor\n"
         "final class " class-name ": XCTestCase {\n\n"
         (->> (:scenarios feature)
              (mapcat (fn [scenario] (map #(method feature scenario %) (rows scenario))))
              (str/join "\n"))
         "}\n")))

(defn feature-ir?
  "An APS feature IR names the feature and carries its scenarios."
  [ir]
  (boolean (and (:name ir) (:scenarios ir))))

(defn source
  "The complete generated Swift file for `features`, in the given order."
  [features]
  (str "// Generated by acceptance/generate.clj from the APS intermediate\n"
       "// representation. Do not edit by hand — rerun bin/acceptance.\n\n"
       "import XCTest\n@testable import Sotto\n\n"
       (->> features (map class-source) (str/join "\n"))))
